name: Go

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      PORT: 5432  
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.17', '1.18', '1.19']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build-DB
        run: docker-compose build
      
      - name: Create-DB
        run: docker-compose up -d

      - name: Test
        run: go test -v ./...
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -o programa main.go   # força o nome do binário

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: programa
          path: programa   # agora o arquivo existe e será enviado

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  Deploy_EC2:
    needs: build
    uses: ./.github/workflows/EC2.yml
    secrets: inherit
